# Generated by Django 5.2.8 on 2025-12-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_department_alter_employee_empname_employee_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
